/**
 * Database schema (Drizzle ORM + PostgreSQL).
 *
 * This is the single source of truth for the database structure. `drizzle-kit`
 * reads this file to generate SQL migrations.
 *
 * Design notes:
 * - IDs are UUIDs generated by Postgres (`gen_random_uuid()`), so the client
 *   never has to coordinate ID generation.
 * - Document *content* is NOT stored as text. It's stored as binary Yjs state
 *   (`bytea`), because the CRDT is the source of truth, not a plain string.
 * - Tenant isolation is enforced at query time by always joining `memberships`
 *   against the authenticated user — see packages/db/src/queries.ts (added later).
 */
import {
  pgTable,
  pgEnum,
  uuid,
  text,
  timestamp,
  bigserial,
  customType,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

/**
 * Postgres `bytea` (raw bytes) mapped to a JS Uint8Array.
 * Yjs updates and snapshots are binary blobs, so we need a bytes column type.
 */
const bytea = customType<{ data: Uint8Array; default: false }>({
  dataType() {
    return "bytea";
  },
});

/** A user's permission level on a single document. */
export const roleEnum = pgEnum("role", ["owner", "editor", "viewer"]);

/* -------------------------------------------------------------------------- */
/* Users                                                                      */
/* -------------------------------------------------------------------------- */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  name: text("name"),
  image: text("image"),
  /**
   * Argon2/bcrypt hash of the password. NEVER store plaintext passwords.
   * Nullable so we can later add OAuth users who have no password.
   */
  passwordHash: text("password_hash"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/* -------------------------------------------------------------------------- */
/* Documents                                                                  */
/* -------------------------------------------------------------------------- */

export const documents = pgTable("documents", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  title: text("title").notNull().default("Untitled"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/* -------------------------------------------------------------------------- */
/* Memberships — who can access a document, and at what role                  */
/* -------------------------------------------------------------------------- */

export const memberships = pgTable(
  "memberships",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: roleEnum("role").notNull().default("viewer"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // A user has exactly one role per document.
    uniqueIndex("memberships_doc_user_unique").on(t.documentId, t.userId),
    // Fast "list documents for this user" lookups.
    index("memberships_user_idx").on(t.userId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Document state — the compacted CRDT snapshot (fast load path)              */
/* -------------------------------------------------------------------------- */

/**
 * One row per document: the latest merged Yjs state as binary.
 * Loading a doc reads this single row instead of replaying the whole update log.
 * The sync server rewrites it (debounced) as edits come in.
 */
export const docState = pgTable("doc_state", {
  documentId: uuid("document_id")
    .primaryKey()
    .references(() => documents.id, { onDelete: "cascade" }),
  state: bytea("state").notNull(),
  stateVector: bytea("state_vector"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/* -------------------------------------------------------------------------- */
/* Document update log — append-only stream of Yjs deltas                     */
/* -------------------------------------------------------------------------- */

/**
 * Append-only log of incremental Yjs updates. Useful for auditing and for
 * clients that reconnect with an old state vector. Periodically compacted
 * into `docState` and truncated to bound growth (see ARCHITECTURE.md).
 */
export const docUpdates = pgTable(
  "doc_updates",
  {
    seq: bigserial("seq", { mode: "number" }).primaryKey(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    update: bytea("update").notNull(),
    clientId: text("client_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("doc_updates_doc_seq_idx").on(t.documentId, t.seq)],
);

/* -------------------------------------------------------------------------- */
/* Versions — user-captured time-travel snapshots                            */
/* -------------------------------------------------------------------------- */

export const versions = pgTable(
  "versions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    /** Encoded Yjs snapshot (state vector + delete set) at capture time. */
    snapshot: bytea("snapshot").notNull(),
    authorId: uuid("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("versions_doc_idx").on(t.documentId, t.createdAt)],
);

/* -------------------------------------------------------------------------- */
/* Inferred TypeScript types (use these across the app)                       */
/* -------------------------------------------------------------------------- */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Document = typeof documents.$inferSelect;
export type Membership = typeof memberships.$inferSelect;
export type Role = (typeof roleEnum.enumValues)[number];
export type Version = typeof versions.$inferSelect;
